.TH hostupd 1 "Apr 2011" "hostupd 0.93"
.SH NAME
hostupd - update a dns record using the ddns mechanism
.SH SYNOPSIS
.SY hostupd
.RI add
.RI <domain[.full.suffix.]>
.RI <rdata>
.OP \-s server
.OP \-t type
.OP \-z zone
.OP \-l ttl
.OP \-u
.OP \-f
.OP \-n
.OP \-q
.OP \-p
.OP \-v
.OP \-\-version
.YS
.SY hostupd
.RI del
.RI <domain[.full.suffix.]>
.RI [rdata]
.OP \-s server
.OP \-t type
.OP \-z zone
.OP \-l ttl
.OP \-u
.OP \-f
.OP \-n
.OP \-q
.OP \-p
.OP \-v
.OP \-\-version
.YS

.SH DESCRIPTION
hostupd is a command-line tool for easy dynamic dns zone updating.
.SH PREREQUISITES
hostupd is based on perl and the Net::DNS perl module.
.SH PARAMETERS
.TP
.BI domain
The domain name to update. hostupd supports both relative and absolute (fully qualified, FQDN) domain names. For relative domain names, hostupd will try to auto-detect the domain suffix. For using absolute domain names, use a trailing dot. e.g.: 'test.foo.com.'
.TP
.B rdata
The record data (or value) to modify for the provided domain. For instance, when using an A record (default) - the rdata should be the IPv4 address. When using a TXT record, rdata is a free text string. rdata is required on
.B add
mode, and is optional on
.B del
mode. If not supplied on del mode, hostupd will delete all found records of the given type.
.SH OPTIONS
.TP
.BI \-h\ \-\-help
Display a short help screen.
.TP
.BI \-f
Force: don't stop on errors if possible.
.TP
.BI \-l\ <ttl>
Set a TTL (Time To Live) value of the record, overriding the DNS server's default.
.TP
.BI \-n
Do-nothing mode on: don't commit the changes to the name server.
.TP
.BI \-p
Do
.B NOT
add a PTR record automatically when adding an A record. Add just the A record.
Same goes for deleting an A record: hostupd won't delete the PTR as well.
.TP
.BI \-q
Quiet mode on: display nothing but error messages.
.TP
.BI \-s\ <server>
Specify a DNS server, overriding the default.
.TP
.BI \-t\ <type>
Set the record type to change (both add or remove). If not provided, A record is used as default.
.TP
.BI \-u
Update a record if it already exists: actually deletes the current record and then adds the requested record.
.TP
.BI \-v
Verbose mode on: displays much more info.
.TP
.BI \-z
Specify the zone to use, overriding the default zone. This is frequently needed when hostupd cannot deduce the zone from /etc/reoslv.conf.
.SH EXAMPLES
.TP
.B hostupd add mydomain 192.168.0.1
Adds an A record to "mydomain". As -p isn't provided, the script automatically adds a PTR record (for reverse resolutions) as well.
.TP
.B hostupd add mydomain test -t TXT -l 3600
Adds a TXT record to "mydomain", which contains the string 'test', and has a TTL of 3600 seconds.
.TP
.B hostupd del mydomain
Deletes all the
.B A
records of "mydomain".
.TP
.B hostupd del mydomain 192.168.0.1
Deletes the
.B A
record which contains 192.168.0.1 of "mydomain".
.TP
.B hostupd del mydomain.foo.bar. -t MX
Deletes all the MX records of "mydomain.foo.bar" (FQDN- note the trailing dot, which must appear when we don't want to add the default domain suffix)
.SH AUTHOR
Hostupd was written by Oren Held.
contact: oren at held.org.il
