# Yes, I know it's a lame Makefile.

# You may want to modify this default PREFIX:
PREFIX=/usr/local
BIN_DIR=$(PREFIX)/bin
MAN_DIR=$(PREFIX)/man

install: 
	cp hostupd $(BIN_DIR)
	cp hostupd_conf.pm $(BIN_DIR)
	cp hostupd.1 $(MAN_DIR)/man1
